#include "SNVariant/Variant.h"
#include <iostream>
#include <string>

using namespace std;
using namespace SurgeNight;

int main()
{
    bool b = true;
    int i = 123;
    unsigned int ui = 432;
    float f = 345.6f;
    double d = 0.5678;
    char ch = 'V';
    unsigned char uch = 'S';
    string str = "Heelo";
    Variant t;
    cout << " -------------- Variant t -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t<< endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t<< endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t<< endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t<< endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t<< endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t<< endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t<< endl;
    t = b;
    cout << " -------------- t = bool -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t<< endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t<< endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t<< endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t<< endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t<< endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t<< endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t<< endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t<< endl;
    t = i;
    cout << " -------------- t = int -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = ui;
    cout << " -------------- t = unsigned int -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = f;
    cout << " -------------- t = float -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = d;
    cout << " -------------- t = double -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = ch;
    cout << " -------------- t = char -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = uch;
    cout << " -------------- t = unsigned char -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;
    t = str;
    cout << " -------------- t = std::string -----------" << endl;
    cout << t.isBool() << ' ' << t.asBool() << ' ' << t << endl;
    cout << t.isInt() << ' ' << t.asInt() << ' ' << t << endl;
    cout << t.isUInt() << ' ' << t.asUInt() << ' ' << t << endl;
    cout << t.isFloat() << ' ' << t.asFloat() << ' ' << t << endl;
    cout << t.isDouble() << ' ' << t.asDouble() << ' ' << t << endl;
    cout << t.isChar() << ' ' << t.asChar() << ' ' << t << endl;
    cout << t.isUChar() << ' ' << t.asUChar() << ' ' << t << endl;
    cout << t.isString() << ' ' << t.asString() << ' ' << t << endl;

    Variant tt(0.0f);
    tt = t;
    cout << " -------------- tt(float) = t(std::string) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = uch;
    tt = t;
    cout << " -------------- tt(std::string) = t(unsigned char) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = ch;
    tt = t;
    cout << " -------------- tt(unsigned char) = t(char) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = d;
    tt = t;
    cout << " -------------- tt(char) = t(double) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = f;
    tt = t;
    cout << " -------------- tt(double) = t(float) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = ui;
    tt = t;
    cout << " -------------- tt(float) = t(unsigned int) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = i;
    tt = t;
    cout << " -------------- tt(unsigned int) = t(int) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    t = b;
    tt = t;
    cout << " -------------- tt(int) = t(bool) -----------" << endl;
    cout << tt.isBool() << ' ' << tt.asBool() << ' ' << tt << endl;
    cout << tt.isInt() << ' ' << tt.asInt() << ' ' << tt << endl;
    cout << tt.isUInt() << ' ' << tt.asUInt() << ' ' << tt << endl;
    cout << tt.isFloat() << ' ' << tt.asFloat() << ' ' << tt << endl;
    cout << tt.isDouble() << ' ' << tt.asDouble() << ' ' << tt << endl;
    cout << tt.isChar() << ' ' << tt.asChar() << ' ' << tt << endl;
    cout << tt.isUChar() << ' ' << tt.asUChar() << ' ' << tt << endl;
    cout << tt.isString() << ' ' << tt.asString() << ' ' << tt << endl;
    Variant list = ListVariant{Variant(1), Variant("dsf"), Variant(true), Variant(2.8f), Variant(0.56), Variant('X')};
    // Variant list = ListVariant{1, "dsf", true, 2.8f, 0.56, 'X'};
    cout << " -------------- list -----------" << endl;
    cout << list.isBool() << ' ' << list.asBool() << ' ' << list << endl;
    cout << list.isInt() << ' ' << list.asInt() << ' ' << list << endl;
    cout << list.isUInt() << ' ' << list.asUInt() << ' ' << list << endl;
    cout << list.isFloat() << ' ' << list.asFloat() << ' ' << list << endl;
    cout << list.isDouble() << ' ' << list.asDouble() << ' ' << list << endl;
    cout << list.isChar() << ' ' << list.asChar() << ' ' << list << endl;
    cout << list.isUChar() << ' ' << list.asUChar() << ' ' << list << endl;
    cout << list.isString() << ' ' << list.asString() << ' ' << list << endl;
    cout << list.isList() << ' ' << list.isObject() << ' ' << list << endl;
    Variant obj = ObjectVariant{{"a", Variant(1)}, {"b", Variant("dsf")}, {"c", Variant(true)}, {"d", Variant(2.8f)}, {"E", Variant(0.56)}, {"f", Variant('X')}};
    cout << " -------------- obj -----------" << endl;
    cout << obj.isBool() << ' ' << obj.asBool() << ' ' << obj << endl;
    cout << obj.isInt() << ' ' << obj.asInt() << ' ' << obj << endl;
    cout << obj.isUInt() << ' ' << obj.asUInt() << ' ' << obj << endl;
    cout << obj.isFloat() << ' ' << obj.asFloat() << ' ' << obj << endl;
    cout << obj.isDouble() << ' ' << obj.asDouble() << ' ' << obj << endl;
    cout << obj.isChar() << ' ' << obj.asChar() << ' ' << obj << endl;
    cout << obj.isUChar() << ' ' << obj.asUChar() << ' ' << obj << endl;
    cout << obj.isString() << ' ' << obj.asString() << ' ' << obj << endl;
    cout << obj.isList() << ' ' << obj.isObject() << ' ' << obj << endl;
    return 0;
}
